general.import = [
  "~/.config/alacritty/themes/themes/dracula_plus.toml"
]

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-c", "tmux new-session -A -s alacritty_$(date +%s)", "exec $SHELL"]

[window]
dimensions = { columns = 90, lines = 40 }
padding = { x = 10, y = 10 }
opacity = 0.93
blur = true
dynamic_title = true

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control"

